dbt-civis:
  target: "{{ env_var('DBT_TARGET') }}"
  default: redshift_adapter
  outputs:
    redshift_adapter:
      type: "{{ env_var('DATABASE_TYPE', 'redshift') }}"
      host: "{{ env_var('DATABASE_HOST') }}"
      port: "{{ env_var('DATABASE_PORT') | as_number }}"
      user: "{{ env_var('DATABASE_USERNAME') }}"
      pass: "{{ env_var('DATABASE_PASSWORD') }}"
      dbname: "{{ env_var('DATABASE_NAME') }}"
      schema: "{{ env_var('DATABASE_SCHEMA') }}"
      threads: 4
    bigquery_oauth_adapter:
      threads: 4
      type: "{{ env_var('DATABASE_TYPE') }}"

      dbname: "{{ env_var('DATABASE_NAME') }}"
      schema: "{{ env_var('DATABASE_SCHEMA', 'default_schema') }}"

      method: "{{ env_var('GCP_AUTH_METHOD') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      refresh_token: "{{ env_var('GCP_REFRESH_TOKEN') }}"

      token_uri: "{{ env_var('GCP_AUTHORIZATION_URI') }}"
      client_id: "{{ env_var('GCP_CLIENT_ID') }}"
      client_secret: "{{ env_var('GCP_CLIENT_SECRET') }}"

    bigquery_service_account_adapter:
      threads: 4
      method: "{{ env_var('GCP_AUTH_METHOD') }}"
      type: "{{ env_var('DATABASE_TYPE') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      schema: "{{ env_var('DBT_DATASET_NAME') }}"
      keyfile: "{{ env_var('GCP_SERVICE_ACCOUNT_KEYFILE_JSON') }}"
