dbt-civis:
  target: redshift_adapter
  outputs:
    redshift_adapter:
      type: "{{ env_var('DB_TYPE') }}"
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT') | as_number }}"
      user: "{{ env_var('DB_CREDENTIAL_USERNAME') }}"
      pass: "{{ env_var('DBT_ENV_SECRET_DB_CREDENTIAL_PASSWORD') }}"
      dbname: "{{ env_var('DB_DATABASE') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 4

    bigquery_service_account_adapter:
      type: "{{ env_var('DATABASE_TYPE') }}"
      method: "{{ env_var('GCP_AUTH_METHOD') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      keyfile: "{{ env_var('GCP_SERVICE_ACCOUNT_KEYFILE_JSON') }}"
      threads: 4

    bigquery_oauth_adapter:
      threads: 4 # Must be a value of 1 or greater
      type: "{{ env_var('DATABASE_TYPE') }}"
      method: "{{ env_var('GCP_AUTH_METHOD') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      token: "{{ env_var('DBT_ENV_SECRET_GCP_ACCESS_TOKEN') }}"
