dbt-civis:
  default: redshift_adapter
  outputs:
    redshift_adapter:
      type: "{{ env_var('DATABASE_TYPE') }}"
      host: "{{ env_var('DATABASE_HOST') }}"
      port: "{{ env_var('DATABASE_PORT') | as_number }}"
      user: "{{ env_var('DATABASE_USERNAME') }}"
      pass: "{{ env_var('DATABASE_PASSWORD') }}"
      dbname: "{{ env_var('DATABASE_NAME') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 4

    bigquery_service_account_adapter:
      type: "{{ env_var('DATABASE_TYPE') }}"
      method: "{{ env_var('GCP_AUTH_METHOD') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      keyfile: "{{ env_var('GCP_SERVICE_ACCOUNT_KEYFILE_JSON') }}"
      threads: 4

    bigquery_oauth_adapter:
      threads: 4 # Must be a value of 1 or greater
      type: "{{ env_var('DATABASE_TYPE') }}"
      method: "{{ env_var('GCP_AUTH_METHOD') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      refresh_token: "{{ env_var('DATABASE_PASSWORD') }}"
      client_id: "{{ env_var('GCP_CLIENT_ID') }}"
      client_secret: "{{ env_var('GCP_CLIENT_SECRET') }}"
      scopes: "https://www.googleapis.com/auth/bigquery, https://www.googleapis.com/auth/userinfo.email"
      token_uri: "{{ env_var('GCP_TOKEN_CREDENTIAL_URI') }}"
