dbt-civis:
  target: redshift_adapter
  outputs:
    redshift_adapter:
      type: "{{ env_var('DATABASE_TYPE') }}"
      host: "{{ env_var('DATABASE_HOST') }}"
      port: "{{ env_var('DATABASE_PORT') | as_number }}"
      user: "{{ env_var('DATABASE_USERNAME') }}"
      pass: "{{ env_var('DBT_ENV_SECRET_DATABASE_PASSWORD') }}"
      dbname: "{{ env_var('DATABASE_NAME') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 4

    bigquery_service_account_adapter:
      type: "{{ env_var('DATABASE_TYPE') }}"
      method: "{{ env_var('GCP_AUTH_METHOD') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      keyfile: "{{ env_var('GCP_SERVICE_ACCOUNT_KEYFILE_JSON') }}"
      threads: 4

    bigquery_oauth_adapter:
      threads: 4 # Must be a value of 1 or greater
      type: "{{ env_var('DATABASE_TYPE') }}"
      method: "{{ env_var('GCP_AUTH_METHOD') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      token: "{{ env_var('DBT_ENV_SECRET_GCP_ACCESS_TOKEN') }}"



#############################################
########## dbt in Civis Studios #############
#############################################

# Civis Studios have slightly different environment variables than
# dbt scripts in Platform (see the dbt-civis profile above for comparison).
#
# The following profile demonstrates the necessary configuration to use dbt in the Civis Studio environment.
# For a database parameter named "civis_consumers":
#  "params": [
#    {
#        "name": "civis_consumers",
#        "description": null,
#        "type": "database",
#        "value": "{\"credential\":1234,\"database\":5678}"
#    }, {
#        "name": "dbt_schema",
#        "description": null,
#        "type": "string",
#        "value": "my_dbt_schema"
#    }
#  ]
# , the corresponding environment variables in Civis Studios are:
civis-studio:
  target: redshift_adapter
  outputs:
    redshift_adapter:
      type: "{{ env_var('CIVIS_CONSUMER_TYPE') }}"
      host: "{{ env_var('CIVIS_CONSUMER_HOST') }}"
      port: "{{ env_var('CIVIS_CONSUMER_PORT') | as_number }}"
      user: "{{ env_var('CIVIS_CONSUMER_CREDENTIAL_USERNAME') }}" # note the _CREDENTIAL
      pass: "{{ env_var('DBT_ENV_SECRET_CIVIS_CONSUMER_CREDENTIAL_PASSWORD') }}" # note the _CREDENTIAL
      dbname: "{{ env_var('CIVIS_CONSUMER_DATABASE') }}" # _DATABASE instead of _NAME
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 4

    bigquery_oauth_adapter:
      threads: 4 # Must be a value of 1 or greater
      type: "{{ env_var('CIVIS_CONSUMER_TYPE') }}"
      method: "{{ env_var('CIVIS_CONSUMER_GCP_AUTH_METHOD') }}"
      project: "{{ env_var('CIVIS_CONSUMER_GCP_PROJECT_ID') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      token: "{{ env_var('DBT_ENV_SECRET_CIVIS_CONSUMER_GCP_ACCESS_TOKEN') }}"

    # If you'd like to connect to BigQuery using a service account, you can do so by 
    # writing the credential password (`CIVIS_CONSUMER_CREDENTIAL_PASSWORD` in this example)
    # to a new file of your choice, then add a `keyfile` param with the file path. 
    # Be careful not to commit the keyfile to source control.
    bigquery_service_account_adapter:
      type: "{{ env_var('CIVIS_CONSUMER_TYPE') }}"
      method: "{{ env_var('CIVIS_CONSUMER_GCP_AUTH_METHOD') }}"
      project: "{{ env_var('CIVIS_CONSUMER_GCP_PROJECT_ID') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      keyfile: "path/to/keyfile.json" # replace this with the path to your keyfile
      threads: 4

