version: 2.1
jobs:
  js_lint:
    docker:
      - image: cimg/node:14.21
    steps:
      - checkout
      - run: |
         cd javascript
         npm install
         npm run lint
  python_lint:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run: |
          cd python
          pip install --disable-pip-version-check --user -r requirements.txt
          /home/circleci/.local/bin/flake8 **/*.py

workflows:
  version: 2
  all_tests:
    jobs:
      - js_lint
      - python_lint
